module.exports = {
  content: ['../blog.html', '../youtube.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#87bfbc',
        'surface-variant': '#353534',
        'inverse-surface': '#e5e2e1',
        'on-primary-fixed': '#00201f',
        'on-secondary-fixed': '#00201f',
        'on-secondary': '#003735',
        background: '#131313',
        'on-error': '#690005',
        'surface-dim': '#131313',
        'inverse-on-surface': '#313030',
        'on-secondary-fixed-variant': '#104f4d',
        'secondary-fixed-dim': '#98d1ce',
        'secondary-fixed': '#b4edea',
        'surface-container-high': '#2a2a2a',
        'outline-variant': '#3d4948',
        'on-tertiary-fixed-variant': '#2a4c4c',
        'on-primary-container': '#00302e',
        'on-error-container': '#ffdad6',
        primary: '#72d7d3',
        'on-background': '#e5e2e1',
        'tertiary-fixed-dim': '#a9cdcc',
        'primary-container': '#34a09c',
        'surface-container-lowest': '#0e0e0e',
        'tertiary-container': '#749796',
        'on-surface-variant': '#bdc9c8',
        'on-tertiary': '#113635',
        outline: '#879392',
        'surface-tint': '#72d7d3',
        'primary-fixed-dim': '#72d7d3',
        'on-primary': '#003736',
        'tertiary-fixed': '#c4eae8',
        'surface-bright': '#393939',
        'surface-container-highest': '#353534',
        surface: '#131313',
        error: '#ffb4ab',
        'on-tertiary-container': '#092f2f',
        'error-container': '#93000a',
        secondary: '#98d1ce',
        'on-primary-fixed-variant': '#00504e',
        'surface-container': '#201f1f',
        tertiary: '#a9cdcc',
        'secondary-container': '#104f4d',
        'on-tertiary-fixed': '#002020',
        'primary-fixed': '#8ff3ef',
        'on-surface': '#e5e2e1',
        'inverse-primary': '#006a67',
        'surface-container-low': '#1c1b1b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        xs: '8px',
        xl: '80px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        base: '4px',
        sm: '16px',
        md: '24px',
        lg: '48px',
      },
      fontFamily: {
        'headline-lg': ['Playfair Display'],
        'label-sm': ['JetBrains Mono'],
        'headline-md': ['Playfair Display'],
        'headline-lg-mobile': ['Playfair Display'],
        'headline-xl': ['Playfair Display'],
        'body-md': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['36px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.1', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
